### ISSUE TITLE
problem?

### ISSUE THREAD

**Issue by CruxVelox** [ZQPei/Sorting_Visualization#8]
### Is this problem from the code or from my pc? ###

`PS C:\Users\cruxv\Desktop\Python\Ordinatore Interi\Sorting_Visualization-master> python3 main.py
pygame 2.5.2 (SDL 2.28.3, Python 3.11.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Preparing sound dict ...
Traceback (most recent call last):
  File "C:\Users\cruxv\Desktop\Python\Ordinatore Interi\Sorting_Visualization-master\main.py", line 55, in <module>
    ds=DataSeq(Length, time_interval=Interval,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cruxv\Desktop\Python\Ordinatore Interi\Sorting_Visualization-master\src\data.py", line 50, in __init__
    self.GetSoundArray()
  File "C:\Users\cruxv\Desktop\Python\Ordinatore Interi\Sorting_Visualization-master\src\data.py", line 116, in GetSoundArray
    self.sound_mixer = list(map(pygame.sndarray.make_sound, self.sound_list))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cruxv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pygame\sndarray.py", line 92, in make_sound
    return mixer.Sound(array=array)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Array must be 2-dimensional for stereo mixer`

**Comment by Samthemanlol** [comment]
I think its the code because i got the same output
